// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateNewRepo(): $CancellablePromise<string> {
    return $Call.ByID(3072097127);
}

export function GetCurrentNotespace(): $CancellablePromise<$models.Notespace> {
    return $Call.ByID(616798964).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetEditorState(): $CancellablePromise<$models.EditorState> {
    return $Call.ByID(2140924809).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetNotespaceFromPaths(paths: string[]): $CancellablePromise<$models.Notespace[]> {
    return $Call.ByID(65555435, paths).then(($result: any) => {
        return $$createType2($result);
    });
}

export function OpenExisitingRepo(): $CancellablePromise<string> {
    return $Call.ByID(2582740457);
}

export function OpenRepoDirectory(dir: string): $CancellablePromise<string> {
    return $Call.ByID(1950941394, dir);
}

// Private type creation functions
const $$createType0 = $models.Notespace.createFrom;
const $$createType1 = $models.EditorState.createFrom;
const $$createType2 = $Create.Array($$createType0);
