// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Create(): $CancellablePromise<string> {
    return $Call.ByID(3167425695);
}

export function PollStream(max: number): $CancellablePromise<$models.StreamEvent[]> {
    return $Call.ByID(1655857422, max).then(($result: any) => {
        return $$createType1($result);
    });
}

export function PollTree(): $CancellablePromise<$models.Node | null> {
    return $Call.ByID(1783588946).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Rescan(): $CancellablePromise<void> {
    return $Call.ByID(667146907);
}

export function StartScan(root: string): $CancellablePromise<void> {
    return $Call.ByID(1696141040, root);
}

export function StopScan(): $CancellablePromise<void> {
    return $Call.ByID(986157398);
}

// Private type creation functions
const $$createType0 = $models.StreamEvent.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Node.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
