// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateNewRepo(): $CancellablePromise<string> {
    return $Call.ByID(3072097127);
}

export function GetEditorState(): $CancellablePromise<$models.EditorState> {
    return $Call.ByID(2140924809).then(($result: any) => {
        return $$createType0($result);
    });
}

export function PollStream(max: number): $CancellablePromise<$models.StreamEvent[]> {
    return $Call.ByID(1655857422, max).then(($result: any) => {
        return $$createType2($result);
    });
}

export function PollTree(): $CancellablePromise<$models.Node | null> {
    return $Call.ByID(1783588946).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Rescan(): $CancellablePromise<void> {
    return $Call.ByID(667146907);
}

export function StartScan(root: string): $CancellablePromise<void> {
    return $Call.ByID(1696141040, root);
}

export function StopScan(): $CancellablePromise<void> {
    return $Call.ByID(986157398);
}

// Private type creation functions
const $$createType0 = $models.EditorState.createFrom;
const $$createType1 = $models.StreamEvent.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.Node.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
