// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetFileData(path: string): $CancellablePromise<string> {
    return $Call.ByID(118238128, path);
}

export function GetFileTree(root: string): $CancellablePromise<$models.Node> {
    return $Call.ByID(295743568, root).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveFileData(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(2669828497, path, content);
}

// Private type creation functions
const $$createType0 = $models.Node.createFrom;
