// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class Node {
    "name": string;
    "path": string;

    /**
     * "file" | "dir" | "symlink"
     */
    "type": string;
    "size": number;
    "modified": time$0.Time;
    "children"?: Node[];
    "isHidden": boolean;
    "extension"?: string;

    /** Creates a new Node instance. */
    constructor($$source: Partial<Node> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("modified" in $$source)) {
            this["modified"] = null;
        }
        if (!("isHidden" in $$source)) {
            this["isHidden"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Node instance from a string or object.
     */
    static createFrom($$source: any = {}): Node {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField5_0($$parsedSource["children"]);
        }
        return new Node($$parsedSource as Partial<Node>);
    }
}

// Private type creation functions
const $$createType0 = Node.createFrom;
const $$createType1 = $Create.Array($$createType0);
