// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    "name": string;
    "description"?: string;
    "repository"?: string;
    "homepage"?: string;
    "registry": { [_: string]: string };
    "author"?: string;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("registry" in $$source)) {
            this["registry"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("registry" in $$parsedSource) {
            $$parsedSource["registry"] = $$createField4_0($$parsedSource["registry"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

export class EditorState {

    /** Creates a new EditorState instance. */
    constructor($$source: Partial<EditorState> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditorState instance from a string or object.
     */
    static createFrom($$source: any = {}): EditorState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EditorState($$parsedSource as Partial<EditorState>);
    }
}

export class Notespace {
    "config": Config | null;
    "path": string;

    /** Creates a new Notespace instance. */
    constructor($$source: Partial<Notespace> = {}) {
        if (!("config" in $$source)) {
            this["config"] = null;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Notespace instance from a string or object.
     */
    static createFrom($$source: any = {}): Notespace {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField0_0($$parsedSource["config"]);
        }
        return new Notespace($$parsedSource as Partial<Notespace>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = Config.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
