export type Status =
	| "FAILED_DIALOG"
	| "INFO_USER_CANCELLED"
	| "WARN_NO_GIT_INIT"
	| "INFO_CONFIG_EXISTS"
	| "FAILED_CONFIG_CHECK"
	| "WARN_NO_CONFIG_CREATE"
	| "WARN_NO_CONFIG_WRITE"
	| "SUCCESS";
